apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: winners  # Nombre del tópico "winners"
  namespace: kafka  # El namespace donde estás desplegando Kafka
  labels:
    strimzi.io/cluster: my-cluster  # El cluster de Kafka con el que se relaciona
spec:
  partitions: 1  # Número de particiones
  replicas: 1    # Número de réplicas

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: losers  # Nombre del tópico "losers"
  namespace: kafka  # El namespace donde estás desplegando Kafka
  labels:
    strimzi.io/cluster: my-cluster  # El cluster de Kafka con el que se relaciona
spec:
  partitions: 1  # Número de particiones
  replicas: 1    # Número de réplicas
