apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: go-api
        image: gcr.io/ht-sopes/go-api
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-api-service
spec:
  type: LoadBalancer
  ports:
    - port: 80          # Puerto expuesto
      targetPort: 8080  # Puerto en el pod donde está escuchando la aplicación
  selector:
    app: go-api  # Este debe coincidir con las etiquetas de tus pods
